name: ccs-data-provider

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - black
  - isort
  - pip:
      - aiohttp==3.8.4
      - mypy-extensions==0.4.3
      - pymongo==3.13.0
      - pymongo-stubs==0.2.0

